### ISSUE TITLE
沟通组件化问题遇到的难点

### ISSUE THREAD

**Issue by hongqinghe** [DSAppTeam/ComponentCornerstone#4]
你好，该组件化架构可以很好的解决组件依赖，可达到高复用，但是如果说业务模块需要业务中的一个单一功能，整个依赖势必会造成依赖方的包增大，怎么样解决这样的一个问题；
还有目前类通过接口进行调用，但是资源文件有好的解决方案吗 ，我们想到的是结构中通过实现方式进行资源文件的暴露，但是这样会很繁琐，请问你那边有什么好的解决方案吗？

**Comment by YummyLau** [comment]
资源文件是不考虑处理的。如果处理了资源文件，那实际上就应该是一个完整的aar，其实和常规的module没有区别的。并且，android在编译的时候，会覆盖替换同名的resource资源且上层依赖会替换下层实现，故没有进行暴露。 接口+数据结构用于满足业务逻辑及业务页面的暴露，而资源则是更为细粒度的。我们的项目一般组件已暴露功能或者activity/fragment/widget为主，如果细化到要暴露xml，strings或者png等资源，就应该想清楚，这对于组件而言是否合理。 @hongqinghe

**Comment by hongqinghe** [comment]
嗯嗯，感谢解答，刚才你提到编译时覆盖替换同名的resource，但是每个模块都有单独的资源命名规则，是不能完成同名替换的，请问如果要复用资源，是不是需要资源下沉达到复用

**Comment by YummyLau** [comment]
@hongqinghe 嗯嗯，一般我们的复用资源会下沉到base。“每个模块都有单独的资源命名规则，是不能完成同名替换的”是的，如果你存在编译限制命名规则就会如此。目前我们是这样处理的：
我们的项目很多模块，基本每个模块会用到的资源会放到base。而如果仅仅两个模块用到的资源，你可以放到base，但也可以用同名，然后ignore忽略编译检测就好。  都可以的。

**Comment by hongqinghe** [comment]
好的，谢谢
