### ISSUE TITLE
使用 :: 多层级创建模块，component.gradle 的 include 不与setting中一致

### ISSUE THREAD

**Issue by sophimp** [DSAppTeam/ComponentCornerstone#6]
我现有的项目 setting.gradle 中：
`
include ':debugEntry'
include ':libs:net'
include ':component:explore'
include ':component:mine'
include ':service:account'
include ':libs:base'
include ':app'
`

在component.gradle 中必须:
`
include ':app', ':debugEntry',
            ':explore',
            ':mine',
            ':account'
`
才能正常识别component, 如果跟setting.gradle 中保持一致，识别不了。

我理解的是component.gradle 中的 include ':module_name'  其中module_name 是指
`sdk{
   configuration {
       'module_name' {
       }
   }
}`
声明的吧。
注释中
`//注意：下面使用到的模块命等同于 setting 中申明的模块名，严格遵守规范`
是不是有误导。

接下来我再研究下源码确认一下。。。

**Comment by YummyLau** [comment]
本意是

**Comment by YummyLau** [comment]
本意是 include 可以使用 configuration 申明的 组件，也就是说赋予 include 对象能够调用组件的能力哈
